//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BegginerLevelTask.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ReviewAssignments = new HashSet<ReviewAssignment>();
            this.ReviewAssignments1 = new HashSet<ReviewAssignment>();
            this.ReviewSubmissions = new HashSet<ReviewSubmission>();
            this.ReviewSubmissions11 = new HashSet<ReviewSubmission>();
        }
    
        public long EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string DesignationEmp { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string DepartmentEmp { get; set; }
        public string AddressEmp { get; set; }
        public string EmployeeType { get; set; }
        public string EmailEmp { get; set; }
        public string Status { get; set; }
        public string UserNameEmp { get; set; }
        public string PasswordEmp { get; set; }
        public string PhoneNumEmp { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual tbl_Organisation tbl_Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewAssignment> ReviewAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewAssignment> ReviewAssignments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewSubmission> ReviewSubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewSubmission> ReviewSubmissions11 { get; set; }
    }
}
