//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BegginerLevelTask.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReviewSubmission
    {
        public Nullable<long> ReviewID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> Rating { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Feedback { get; set; }
        public long ReviewSubmissionID { get; set; }
        public Nullable<bool> SubmissionStatus { get; set; }
        public Nullable<long> EmployeeToBeReviewed { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ReviewCreation ReviewCreation { get; set; }
        public virtual Employee Employee11 { get; set; }
    }
}
