//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BegginerLevelTask.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuperUser()
        {
            this.tbl_Organisation = new HashSet<tbl_Organisation>();
        }
    
        public long SuperID { get; set; }
        public string SuperFirstName { get; set; }
        public string SuperLastName { get; set; }
        public string SuperUserName { get; set; }
        public string SuperPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Organisation> tbl_Organisation { get; set; }
    }
}
